#!/usr/bin/env bun
/**
 * Regenerates src/domains.ts from the community-maintained CC0 blocklist
 * (disposable-email-domains/disposable-email-domains). Run manually or in CI
 * to catch drift as new disposable/rotating-alias domains get discovered.
 */

const SOURCE_URL =
  'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf';
const OUTPUT_PATH = new URL('../src/domains.ts', import.meta.url);

const res = await fetch(SOURCE_URL);
if (!res.ok) {
  throw new Error(`Failed to fetch ${SOURCE_URL}: ${res.status} ${res.statusText}`);
}

const text = await res.text();
const domains = text
  .split('\n')
  .map(line => line.trim().toLowerCase())
  .filter(line => line.length > 0 && !line.startsWith('#'));

const uniqueSorted = [...new Set(domains)].sort();

const body = uniqueSorted.map(d => `  '${d}',`).join('\n');

const output = `// Generated by scripts/sync-domains.ts from
// https://github.com/disposable-email-domains/disposable-email-domains (CC0)
// Run \`bun scripts/sync-domains.ts\` to regenerate.

export const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
${body}
]);
`;

await Bun.write(OUTPUT_PATH, output);
console.error(`Wrote ${uniqueSorted.length} domains to ${OUTPUT_PATH.pathname}`);
